"""
Useful constants
"""

UID = "uid"
TID = "tid"
DATETIME = "datetime"
TIMESTAMP = "timestamp"
LOCATIONSTAMP = "locationstamp"
OCCUPANCY = "occupancy"
ALTITUDE = "alt"
LATITUDE = "lat"
LONGITUDE = "lon"
ORIGINAL_LATITUDE = "original_lat"
ORIGINAL_LONGITUDE = "original_lon"
GT_LATITUDE = "gt_lat"
GT_LONGITUDE = "gt_lon"
OBF_LATITUDE = "obf_lat"
OBF_LONGITUDE = "obf_lon"
ADV_LATITUDE = "adv_lat"
ADV_LONGITUDE = "adv_lon"
MM_STATE = "mm_state"
GT_STATE = "gt_state"
TRAIN = "train"
TEST = "test"
NORM_PROF = "normal"
OMNI_PROF = "omni"
USER = "user"
REPORT = "report"
CHECKED = "checked"
RE_IDENTIFIED = "re_identified"
OBFUSCATED = "obf"
QUALITY_LOSS = "ql"

# Default locations to save data, datasets, and outputs (results and images)
input_folder = "./input/"
datasets_folder = input_folder + "datasets/"
data_folder = input_folder + "data/"
output_folder = "./output/"
results_folder = output_folder + "results/"
images_folder = output_folder + "images/"
